-- MySQL Script generated by MySQL Workbench
-- 12/21/14 03:31:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbparqueadero
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbparqueadero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbparqueadero` ;
USE `dbparqueadero` ;

-- -----------------------------------------------------
-- Table `dbparqueadero`.`parqueadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbparqueadero`.`parqueadero` (
  `idparqueadero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idparqueadero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbparqueadero`.`tipo_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbparqueadero`.`tipo_vehiculo` (
  `idtipo_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `parqueadero_idparqueadero` INT NOT NULL,
  PRIMARY KEY (`idtipo_vehiculo`),
  INDEX `fk_tipo_vehiculo_parqueadero1_idx` (`parqueadero_idparqueadero` ASC),
  CONSTRAINT `fk_tipo_vehiculo_parqueadero1`
    FOREIGN KEY (`parqueadero_idparqueadero`)
    REFERENCES `dbparqueadero`.`parqueadero` (`idparqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbparqueadero`.`tarifa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbparqueadero`.`tarifa` (
  `id_tarifa` INT NOT NULL AUTO_INCREMENT,
  `segundos` MEDIUMTEXT NULL,
  `costo` FLOAT NULL,
  `parqueadero_idparqueadero` INT NOT NULL,
  `tipo_vehiculo_idtipo_vehiculo` INT NOT NULL,
  PRIMARY KEY (`id_tarifa`),
  INDEX `fk_servicio_parqueadero_idx` (`parqueadero_idparqueadero` ASC),
  INDEX `fk_servicio_tipo_vehiculo1_idx` (`tipo_vehiculo_idtipo_vehiculo` ASC),
  CONSTRAINT `fk_servicio_parqueadero`
    FOREIGN KEY (`parqueadero_idparqueadero`)
    REFERENCES `dbparqueadero`.`parqueadero` (`idparqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_tipo_vehiculo1`
    FOREIGN KEY (`tipo_vehiculo_idtipo_vehiculo`)
    REFERENCES `dbparqueadero`.`tipo_vehiculo` (`idtipo_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbparqueadero`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbparqueadero`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` INT NULL,
  `telefono` INT NULL,
  `role` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `sesion` TINYINT(1) NULL,
  `parqueadero_idparqueadero` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_parqueadero1_idx` (`parqueadero_idparqueadero` ASC),
  CONSTRAINT `fk_usuario_parqueadero1`
    FOREIGN KEY (`parqueadero_idparqueadero`)
    REFERENCES `dbparqueadero`.`parqueadero` (`idparqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbparqueadero`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbparqueadero`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `fecha_entrada` DATE NULL,
  `fecha_salida` DATE NULL,
  `placa` VARCHAR(45) NULL,
  `valor` INT NULL,
  `parqueadero_idparqueadero` INT NOT NULL,
  `tipo_vehiculo_idtipo_vehiculo` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idticket`),
  INDEX `fk_ticket_parqueadero1_idx` (`parqueadero_idparqueadero` ASC),
  INDEX `fk_ticket_tipo_vehiculo1_idx` (`tipo_vehiculo_idtipo_vehiculo` ASC),
  INDEX `fk_ticket_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_ticket_parqueadero1`
    FOREIGN KEY (`parqueadero_idparqueadero`)
    REFERENCES `dbparqueadero`.`parqueadero` (`idparqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_tipo_vehiculo1`
    FOREIGN KEY (`tipo_vehiculo_idtipo_vehiculo`)
    REFERENCES `dbparqueadero`.`tipo_vehiculo` (`idtipo_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `dbparqueadero`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
